name: SeveDean
favicon: null
layout_spectrum: 0.6738776669371873
typography_spectrum: 0.17316135461442173
title: Explore Your Universe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fadfca'
    - '#160b11'
    - '#6f7f7c'
    - '#fd3a00'
    - '#c90010'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
