name: SeveDean
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10087
title: Explore Your Universe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8d9bc'
    - '#435d2e'
    - '#679e05'
    - '#ab8673'
    - '#f96959'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
