name: SeveDean
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17316135461442173
title: Explore Your Universe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#ffaf00'
    - '#70ad9e'
    - '#d5060e'
    - '#1a151c'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
