name: SeveDean
favicon: null
layout_spectrum: 0.6738776669371873
typography_spectrum: 0.17316135461442173
title: Explore Your Universe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
